#!/bin/bash

echo "🔄 UPDATING FRONTEND TO USE NEW BACKEND URL"
echo "=============================================="
echo ""
echo "✅ Local environment files updated:"
echo "   - isafari_global/bouncesteps-frontend/.env"
echo "   - isafari_global/bouncesteps-frontend/.env.production"
echo "   - isafari_global/bouncesteps-admin/.env.production"
echo ""
echo "🔧 NEW BACKEND URL:"
echo "   https://bouncesteps-backend-392429231515.us-central1.run.app/api"
echo ""
echo "📋 NEXT STEPS:"
echo ""
echo "1. UPDATE VERCEL ENVIRONMENT VARIABLES:"
echo "   - Go to https://vercel.com/dashboard"
echo "   - Find your bouncesteps project"
echo "   - Go to Settings > Environment Variables"
echo "   - Update these variables:"
echo "     VITE_API_URL=https://bouncesteps-backend-392429231515.us-central1.run.app/api"
echo "     VITE_API_BASE_URL=https://bouncesteps-backend-392429231515.us-central1.run.app/api"
echo ""
echo "2. REDEPLOY YOUR FRONTEND:"
echo "   - Go to Deployments tab"
echo "   - Click 'Redeploy' on the latest deployment"
echo ""
echo "3. TEST THE FIX:"
echo "   - Wait 2-3 minutes for deployment"
echo "   - Go to https://www.bouncesteps.com"
echo "   - Open Developer Tools > Console"
echo "   - Look for: 'API URL IN USE: https://bouncesteps-backend-392429231515.us-central1.run.app/api'"
echo "   - Try to login - CORS errors should be gone!"
echo ""
echo "🎯 EXPECTED RESULT:"
echo "   - No more CORS errors"
echo "   - All API calls should work"
echo "   - Login should work properly"
echo ""